apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: cloudai:latest  # Replace with your Django app image
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: postgres-service  # Service name of PostgreSQL
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: cloudai
        - name: DB_USER
          value: sushil
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # This exposes the service externally
